ref: attempt to run 'variants-switch' action with brew bottle installation

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -18,6 +18,10 @@ inputs:
     description: 'Variant you would like to switch to.'
     required: true
     default: 'default'
+  version:
+    description: "Variant's version."
+    required: true
+    default: 'latest'
   verbose:
     description: 'Log tech details for nerds.'
     required: true
@@ -31,12 +35,55 @@ runs:
       run: |
         echo "project_path=$(pwd)" >> $GITHUB_ENV
           
-    - name: Variants Switch
+    - name: Install variants
       shell: bash
       run: |
+        if [[ "${{ inputs.version }}" == "latest" ]];
+        then
+          echo "Installing variants"
+          brew install backbase/m/variants
+          echo "INSTALLATION_STATUS=$?" >> $GITHUB_ENV
+        else
+          if ! [[ "${{ inputs.version }}" =~ [[:digit:]]\.[[:digit:]]\.[[:digit:]] ]];
+          then
+            echo "INSTALLATION_STATUS=❌ 'version' should match the pattern 'x.y.z'" >> $GITHUB_ENV
+          else
+            version_in_formula=`brew info backbase/m/variants | sed -n 's/.*\(stable [[:digit:]]\.[[:digit:]]\.[[:digit:]]\).*/\1/p' | cut -d ' ' -f2`
+            inputVersion=`echo "${{ inputs.version }}" | sed 's/\.//g'`
+            versionInFormula=`echo "$version_in_formula" | sed 's/\.//g'`
+            echo "input version: $inputVersion"
+            echo "version in formula: $versionInFormula"
+            if [[ $inputVersion -ge $versionInFormula ]];
+            then
+              echo "Installing variants $version_in_formula"
+              brew install backbase/m/variants
+            else
+              echo "Installing variants ${{ inputs.version }}"
+              brew install "backbase/m/variants@${{ inputs.version }}"
+            fi
+            echo "INSTALLATION_STATUS=$?" >> $GITHUB_ENV
+          fi
+        fi
+
+    - name: Handle input failure
+      shell: bash
+      if: ${{ env.INSTALLATION_STATUS != '0' && env.INSTALLATION_STATUS != '1' }}
+      run: |
+        echo "${{ env.INSTALLATION_STATUS }}" 1>&2;
+        exit 1
+
+    - name: Handle installation failure
+      shell: bash
+      if: ${{ env.INSTALLATION_STATUS == '1' }}
+      run: |
+        echo "Failed to install variants. Please ensure the version specified exists." 1>&2;
+        exit 1
+
+    - name: Variants Switch
+      shell: bash
+      if: ${{ env.INSTALLATION_STATUS == '0' }}
+      run: |
         echo "Repository: ${{ github.repository }}"
-        cd ${{ github.action_path }}
-        brew install variants
         cd ${{ env.project_path }}
         
         if [[ ${{ inputs.platform }} == default ]];
